academy/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,  include
from django.conf.urls.static import static

from conta.views import *
from item.views import *
from categoria.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='home'),
    path('item/<id>', ver_item, name='ver_item'),
    path('cadastro/', cadastro, name='cadastro'),
    path('categoria/<id>', categoria, name='categoria'),
    path('pesquisa/', pesquisa, name='pesquisa'),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

avaliacao/models.py
from django.db import models


# Create your models here.
class Avaliacao(models.Model):
    tipo = models.CharField(max_length=255)
    ativo = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tipo
        
    class Meta:
        db_table = "avaliacao"
        verbose_name_plural = "Avaliações"

banner/models.py
from django.db import models
# Create your models here.

class Banner(models.Model):
    titulo = models.CharField(max_length=255, verbose_name="Título")
    arquivo_imagem = models.ImageField(upload_to='banner', verbose_name="Imagem", null=True, blank=True)
    arquivo_video = models.FileField(upload_to='banner', max_length=254, verbose_name="Vídeo", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

    class Meta:
        db_table = "banner"
        verbose_name_plural = "Banners"

categoria/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nome = models.CharField(max_length=255, verbose_name="Categoria")

    def __str__(self):
        return self.nome

    class Meta:
        db_table = "categoria"
        verbose_name_plural = "Categorias"

conta/models.py
from django.db import models

# Create your models here.
class Conta(models.Model):
    cpf = models.CharField(max_length=11, unique=True)
    nome = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255, verbose_name="Endereço")
    email = models.EmailField(unique = True, verbose_name="E-mail")
    senha = models.CharField(max_length=255)
    conf_senha = models.CharField(max_length=255)

    class Meta:
        db_table = "conta"
        verbose_name_plural = "Contas"

imagem/models.py
from django.db import models

from item.models import Item

# Create your models here.
class Imagem(models.Model):
    arquivo_imagem = models.ImageField(upload_to='imagemItem', verbose_name="Imagem")
    item_id = models.ForeignKey(Item,  on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  
    
    class Meta:
        db_table = "imagem"
        verbose_name_plural = "Imagens"

item/models.py
from django.db import models
from categoria.models import *

# Create your models here.
class Item(models.Model):
    titulo = models.CharField(max_length=255, verbose_name='Título')
    descricao = models.TextField(verbose_name="Descrição")
    preco = models.FloatField(verbose_name="Preço")
    categoria_id = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

    class Meta:
        db_table = "item"
        verbose_name_plural = "Itens"

video/models.py
from django.db import models

from item.models import Item


# Create your models here.
class Video(models.Model):
    item_id = models.ForeignKey(Item,on_delete=models.DO_NOTHING)
    arquivo_video = models.CharField(max_length=255, verbose_name="Vídeo")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "video"
        verbose_name_plural = "Vídeos"

conta/forms.py
from django import forms
from .models import *

class FormConta(forms.ModelForm):
    nome= forms.CharField(label = 'Nome', max_length = 255, widget = forms.TextInput(attrs = {'class':'form-control required', 'placeholder': 'Nome'}))
    cpf= forms.CharField(label = 'CPF', max_length = 255, widget = forms.TextInput(attrs = {'class':'form-control required', 'placeholder': 'CPF'}))
    endereco= forms.CharField(label = 'Endereço', max_length = 255, widget = forms.TextInput(attrs = {'class':'form-control required',  'placeholder': 'Endereço'}))
    email= forms.CharField(label = 'E-mail', max_length = 255, widget = forms.EmailInput(attrs = {'class':'form-control required',  'placeholder': 'E-mail'}))
    senha = forms.CharField(label = 'Senha', max_length = 255, widget = forms.PasswordInput(attrs = {'class':'form-control required'}))
    conf_senha= forms.CharField(label = 'Confirme a senha', max_length = 255, widget = forms.PasswordInput(attrs = {'class':'form-control required'}))
    


    class Meta:
        model = Conta
        fields = ['nome', 'endereco', 'cpf', 'email', 'senha', 'conf_senha']

avaliacao/views.py
from django.shortcuts import render

# Create your views here.

banner/views.py
from django.shortcuts import render

# Create your views here.

categoria/views.py
from django.shortcuts import render
from .models import *
from item.models import *

# Create your views here.

def categoria(request, id):
    categoria = Categoria.objects.get(id=id)
    itens = Item.objects.filter(categoria_id=categoria.id)
    categorias = Categoria.objects.all()

    return render(request, "categoria.html", {"categoria": categoria, 'itens': itens, 'categorias': categorias})

conta/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.models import User
from .models import *
from django.http.response import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.hashers import make_password
# Create your views here.

def cadastro(request):
    if request.method == 'POST':
        forms = FormConta(request.POST, request.FILES, instance=Conta(), prefix='')

        if forms.is_valid():
            conta = forms.save(commit=False)

            senha = conta.senha
            conta.senha = make_password(conta.senha)
            conta.conf_senha = conta.senha
            conta.save()
            user = User.objects.create_user(conta.cpf, conta.email, senha)
            nome = conta.nome.split()
            user.first_name = nome[0]
            user.save()
            messages.success(request, "Cadastro do "+conta.cpf+" realizado com sucesso.")
            return redirect('login')  

        messages.info(request, "Cadastro não realizado. ")
        context = {
            'form': forms
        }
        return render(request, 'registration/cadastro.html', context)

    forms = FormConta(instance=Conta(), prefix='')

    context = {
        'form': forms
    }
    return render(request, 'registration/cadastro.html', context)

imagem/views.py
from django.shortcuts import render

# Create your views here.

item/views.py
from django.shortcuts import render

from .models import *
from banner.models import *
from categoria.models import *
from django.db.models import Q

# Create your views here.

def index(request):
    itens = Item.objects.all()
    banner = Banner.objects.all()
    categorias = Categoria.objects.all()

    return render(request, 'index.html', {'itens': itens, 'banners': banner, 'categorias': categorias})


def ver_item(request, id):
    item = Item.objects.get(id=id)
    categorias = Categoria.objects.all()

    return render(request, 'item.html', {'item': item,  'categorias': categorias})

def pesquisa(request):
    pesquisa = request.POST.get('pesquisa')
    tipo = request.POST.get('tipo')
    categorias = Categoria.objects.all()

    if tipo == None:
        itens = Item.objects.filter(titulo=pesquisa)
        return render(request, "itens.html", {"categorias": categorias, "itens": itens})

    itens = Item.objects.filter(
            Q(titulo__istartswith=pesquisa)|  Q(titulo__iendswith=pesquisa) |  Q(titulo__icontains=pesquisa)|
            Q(titulo__startswith=pesquisa)|  Q(titulo__endswith=pesquisa) |
            Q(descricao__istartswith=pesquisa)|  Q(descricao__iendswith=pesquisa) |  Q(descricao__icontains=pesquisa)|
            Q(descricao__startswith=pesquisa)|  Q(descricao__endswith=pesquisa)
        )
    return render(request, "itens.html", {"categorias": categorias, "itens": itens})

video/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <title>Academia</title>
</head>
<body>
    
    <header class="py-3 mb-3 border-bottom">
        <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
          <div class="dropdown">
            <a href="{% url 'home' %}" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none dropdown-toggle" id="dropdownNavLink" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://img.icons8.com/ios/50/000000/heart-monitor.png" width="50" height="50"/>
            </a>
            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownNavLink">
              <li><a class="dropdown-item" href="{% url 'home' %}">Início</a></li>
              <li><hr class="dropdown-divider"></li>
              {% for categoria in categorias %}
                <li><a class="dropdown-item" href="{% url 'categoria' categoria.id %}">{{ categoria.nome }}</a></li>
              {% endfor %}
            </ul>
          </div>
      
          <div class="">
            {% if user.is_authenticated %}
              <div class="d-flex align-items-center">
                <form method="post" action="{% url 'pesquisa' %}" class="w-100 me-3" >
                  {% csrf_token %}
                  <input type="search" class="form-control" name="pesquisa" placeholder="Pesquise...">
                  <div class="form-check form-switch d-flex justify-content-end">
                    <input class="form-check-input" type="checkbox" name="tipo" id="flexSwitchCheckDefault">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Pesquisa avançada</label>
                  </div>
                </form>
                <div class="flex-shrink-0 dropdown">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                        <li><a class="dropdown-item" href="#">Avaliação</a></li>
                        <li><a class="dropdown-item" href="#">Configurações</a></li>
                        <li><a class="dropdown-item" href="#">Perfil</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
                    </ul>
                </div>
              </div>
            {% else %}
                <div>
                    <div class="d-grid gap-2  mx-auto" style="float: right;">
                        <a href="{% url 'login' %}" class="btn btn-outline-info">
                            Entrar
                        </a>
                        <a href="{% url 'cadastro' %}" class="text-center">Cliente novo? cadastrar</a>
                    </div>
                </div>
            {% endif %}
          </div>
        </div>
    </header>

  

    {% block conteudo %}
    {% endblock %}

    <footer class="container py-5">
        <div class="row">
          <div class="col-sm-12 text-center">
            <img src="https://img.icons8.com/ios/50/000000/heart-monitor.png" width="20" height="20"/>
            <small class="d-block mb-3 text-muted">© 2022</small>
          </div>
        </div>
    </footer>
     <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>

templates/categoria.html
{% extends 'base.html' %} 

{% block conteudo  %}

    <section class="container mt-4">
        <h4 class="text-center">{{ categoria.nome }}</h4>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in itens %}
            <a href="{% url 'ver_item' item.id %}">
                <div class="col">
                    <div class="card">
                        <img src="/media/{{ item.imagem_set.first.arquivo_imagem }}" class="card-img-top" alt="item.imagem_set.first.titulo">
                        <div class="card-body">
                        <h5 class="card-title">{{ item.titulo }}</h5>
                        <!-- <p class="card-text"><b>R$ {{ item.preco }}</b></p> -->
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}

        </div>
    </section>

{% endblock %}

templates/compra.html
{% extends 'base.html' %} 

{% block conteudo  %}
<section class="container">
    <div class="row g-5">
        <div class="col-md-5 col-lg-4 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Seu carrinho</span>
            <span class="badge bg-primary rounded-pill">1</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-0">Produto</h6>
                <small class="text-muted">{{ item.titulo }}</small>
              </div>
              <span class="text-muted">R$ {{ item.preco }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Código</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">−R$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total</span>
              <strong>R$ {{ item.preco }}</strong>
            </li>
          </ul>
    
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Código promocional">
              <button type="submit" class="btn btn-secondary">Adicionar código</button>
            </div>
          </form>
        </div>
        <div class="col-md-7 col-lg-8">
          <form class="needs-validation" novalidate="">
            <div class="row g-3">
             
                <h4 class="mb-3">Pagamento</h4>
        
                <div class="my-3">
                    {% for pagamento in pagamentos %}
                    <div class="form-check">
                        <input id="{{ pagamento.id }}" name="metodo" type="radio" class="form-check-input" checked="" required="">
                        <label class="form-check-label" for="{{ pagamento.id }}">{{ pagamento.tipo }}</label>
                    </div>
                    {% endfor %}
                </div>
    
                
                <hr class="my-4">
                <h4 class="mb-3">Forma de entrega</h4>
        
                <div class="my-3">
                    {% for entrega in entregas %}
                    <div class="form-check">
                        <input id="{{ entrega.id }}" name="entrega" type="radio" class="form-check-input" checked="" required="">
                        <label class="form-check-label" for="{{ entrega.id }}">{{ entrega.tipo }}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
    
            <hr class="my-4">
    
            <button class="w-100 btn btn-primary btn-lg" type="submit">Finalizar compra</button>
          </form>
        </div>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends 'base.html' %} 

{% block conteudo  %}

    <section id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 0"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/media/{{ banners.0.arquivo_imagem }}" max-height="200" class="d-block w-100" alt="{{ banners.0.titulo }}">
            </div>
            <div class="carousel-item">
                <img src="/media/{{ banners.1.arquivo_imagem }}" class="d-block w-100" alt="{{ banners.1.titulo }}">
            </div>
            <div class="carousel-item">
                <img src="/media/{{ banners.2.arquivo_imagem }}" class="d-block w-100" alt="{{ banners.2.titulo }}">
            </div>
            <div class="carousel-item">
                <img src="/media/{{ banners.3.arquivo_imagem }}" class="d-block w-100" alt="{{ banners.3.titulo }}">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Próximo</span>
        </button>
    </section>

    <section class="container mt-4">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in itens %}
            <a href="{% url 'ver_item' item.id %}">
                <div class="col">
                    <div class="card">
                        <img src="/media/{{ item.imagem_set.first.arquivo_imagem }}" class="card-img-top" alt="item.imagem_set.first.titulo">
                        <div class="card-body">
                        <h5 class="card-title">{{ item.titulo }}</h5>
                        <!-- <p class="card-text"><b>R$ {{ item.preco }}</b></p> -->
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}

        </div>
    </section>

{% endblock %}

templates/item.html
{% extends 'base.html' %} 

{% block conteudo  %}
    <section class="container ">
        <div class="row">
            <div class="col-6 mt-5">
                <div id="carouselExampleFade" class="carousel  carousel-dark " data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="/media/{{ item.imagem_set.first.arquivo_imagem }}" class="d-block w-100" alt="...">
                      </div>
                      <!-- <div class="carousel-item">
                        <img src="/media/{{ item.imagem_set.all.4.arquivo_imagem }}" class="d-block w-100" alt="...">
                      </div> -->
                      <div class="carousel-item">
                          {{ item.video_set.all.first.arquivo_video| safe }}
                      </div>
                      <div class="carousel-item">
                        <img src="/media/{{ item.imagem_set.all.2.arquivo_imagem }}" class="d-block w-100" alt="...">
                      </div>
                      <!-- <div class="carousel-item">
                        <img src="/media/{{ item.imagem_set.all.3.arquivo_imagem }}" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="/media/{{ item.imagem_set.all.4.arquivo_imagem }}" class="d-block w-100" alt="...">
                      </div> -->
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Anterior</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="col-6">
                <h4>
                    <b>
                        {{ item.titulo }}
                    </b>
                </h4>
                <p>
                    {{ item.descricao | safe }}
                </p>
            </div>
            <!-- <div class="col-3 " style="padding-top: 25%">
                <div class="text-center">
                    <h3>
                        <b >
                           R$ {{ item.preco }}
                        </b>
                    </h3>
                    <div class="d-grid gap-2  mx-auto">
                        <a href="{% url 'compra' item.id %}" class="btn btn-danger" type="button">Comprar</a>
                    </div>
                </div>
            </div> -->

        </div>
    </section>
{% endblock %}

templates/itens.html
{% extends 'base.html' %} 

{% block conteudo  %}

    <section class="container mt-4">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in itens %}
            <a href="{% url 'ver_item' item.id %}">
                <div class="col">
                    <div class="card">
                        <img src="/media/{{ item.imagem_set.first.arquivo_imagem }}" class="card-img-top" alt="item.imagem_set.first.titulo">
                        <div class="card-body">
                        <h5 class="card-title">{{ item.titulo }}</h5>
                        <!-- <p class="card-text"><b>R$ {{ item.preco }}</b></p> -->
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}

        </div>
    </section>

{% endblock %}